package mapping;
// Generated 15 janv. 2018 23:23:09 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Admin generated by hbm2java
 */
@Entity
@Table(name="admin"
    ,catalog="notesdefrais"
)
public class Admin  implements java.io.Serializable {


     private Integer idAdmin;
     private String emailAdmin;
     private String mdpAdmin;

    public Admin() {
    }

    public Admin(String emailAdmin, String mdpAdmin) {
       this.emailAdmin = emailAdmin;
       this.mdpAdmin = mdpAdmin;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_admin", nullable=false)
    public Integer getIdAdmin() {
        return this.idAdmin;
    }
    
    public void setIdAdmin(Integer idAdmin) {
        this.idAdmin = idAdmin;
    }

    
    @Column(name="email_admin", nullable=false, length=50)
    public String getEmailAdmin() {
        return this.emailAdmin;
    }
    
    public void setEmailAdmin(String emailAdmin) {
        this.emailAdmin = emailAdmin;
    }

    
    @Column(name="mdp_admin", nullable=false, length=50)
    public String getMdpAdmin() {
        return this.mdpAdmin;
    }
    
    public void setMdpAdmin(String mdpAdmin) {
        this.mdpAdmin = mdpAdmin;
    }




}


