package mapping;
// Generated 15 janv. 2018 23:23:09 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.id.Assigned;

/**
 * Client generated by hbm2java
 */
@Entity
@Table(name="client"
    ,catalog="notesdefrais"
)
public class Client  implements java.io.Serializable {


     //private Integer idClient;
     public static String nomClient;
     private String adresse;
     private String email;
    private Integer idClient;

    public Client() {
    }

    public Client(String nomClient, String adresse, String email) {
       this.nomClient = nomClient;
       this.adresse = adresse;
       this.email = email;
    }
   
    

    @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="id_societe", nullable=false)
    public Integer getIdClient() {
        return this.idClient;
    }
    
    public void setIdClient(Integer idClient) {
        this.idClient = idClient;
    }
    public String getNomClient() {
        return this.nomClient;
    }
    
    public void setNomClient(String nomClient) {
        this.nomClient = nomClient;
    }

    
    @Column(name="adresse_societe", nullable=false, length=50)
    public String getAdresseClient() {
        return this.adresse;
    }
    
    public void setAdresseClient(String adresseClient) {
        this.adresse = adresseClient;
    }

    
    @Column(name="email_societe", nullable=false, length=50)
    public String getEmailClient() {
        return this.email;
    }
    
    public void setEmailClient(String emailClient) {
        this.email = emailClient;
    }

    @Override
    public String toString() {
        return nomClient;
    }




}


