package mapping;
// Generated 15 janv. 2018 23:23:09 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Hebergement generated by hbm2java
 */
@Entity
@Table(name = "hebergement",
        catalog = "notesdefrais"
)
public class Hebergement implements java.io.Serializable {

    private Integer idHeberg;
    private String cause;
    //private String distanceHerberg;
    //private String tempsHeberg;
    private double montant;
    private double montantAnnexesHeberg;
    private Date dateHeberg;
    private Integer idClient;

    public Hebergement() {
    }

    public Hebergement(String cause, double montant, double montantAnnexesHeberg, Date dateHeberg, Integer idClient) {
        //this.distanceHerberg = distanceHerberg;
        //this.tempsHeberg = tempsHeberg;
        this.cause = cause;
        this.montant = montant;
        this.montantAnnexesHeberg = montantAnnexesHeberg;
        this.dateHeberg = dateHeberg;
        this.idClient = idClient;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id_heberg", unique = true, nullable = false)
    public Integer getIdHeberg() {
        return this.idHeberg;
    }

    public void setIdHeberg(Integer idHeberg) {
        this.idHeberg = idHeberg;
    }

    @Column(name = "montant_heberg", nullable = false, precision = 22, scale = 0)
    public double getMontant() {
        return montant;
    }

    public void setMontant(double montant) {
        this.montant = montant;
    }

    @Column(name = "cause_heberg", nullable = false, length = 50)
    public String getCause() {
        return cause;
    }

    public void setCause(String cause) {
        this.cause = cause;
    }

    /*@Column(name="distance_herberg", nullable=false, length=50)
    public String getDistanceHerberg() {
    return this.distanceHerberg;
    }
    public void setDistanceHerberg(String distanceHerberg) {
    this.distanceHerberg = distanceHerberg;
    }*/
 /*@Column(name = "temps_heberg", nullable = false, length = 50)
    public String getTempsHeberg() {
        return this.tempsHeberg;
    }

    public void setTempsHeberg(String tempsHeberg) {
        this.tempsHeberg = tempsHeberg;
    }*/
    @Column(name = "montantAnnexes_heberg", nullable = false, precision = 22, scale = 0)
    public double getMontantAnnexesHeberg() {
        return this.montantAnnexesHeberg;
    }

    public void setMontantAnnexesHeberg(double montantAnnexesHeberg) {
        this.montantAnnexesHeberg = montantAnnexesHeberg;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "date_heberg", nullable = false, length = 10)
    public Date getDateHeberg() {
        return this.dateHeberg;
    }

    public void setDateHeberg(Date dateHeberg) {
        this.dateHeberg = dateHeberg;
    }

    @Column(name = "id_salarie", unique = true, nullable = false)
    public Integer getIdClient() {
        return idClient;
    }

    public void setIdClient(Integer idClient) {
        this.idClient = idClient;
    }

}
