package mapping;
// Generated 15 janv. 2018 23:23:09 by Hibernate Tools 4.3.1


import java.time.LocalDate;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Restaurant generated by hbm2java
 */
@Entity
@Table(name="restaurant"
    ,catalog="notesdefrais"
)
public class Restaurant  implements java.io.Serializable {


     private Integer idRest;
     private Date dateRest;
     private double montantRest;
     //private int idClient;
     private String nomClient;
     private Integer idSalarie;
     

    public Restaurant() {
    }

    public Restaurant(Date dateRest, double montantRest, int idClient, String nomSociete,Integer idSalarie) {
       this.dateRest = dateRest;
       this.montantRest = montantRest;
       //this.idClient = idClient;
       this.nomClient = nomSociete;
       this.idSalarie = this.idSalarie;
    }

   
    public Integer getIdSalarie() {
        return idSalarie;
    }

    public void setIdSalarie(Integer idSalarie) {
        this.idSalarie = idSalarie;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_rest", unique=true, nullable=false)
    public Integer getIdRest() {
        return this.idRest;
    }
    
    public void setIdRest(Integer idRest) {
        this.idRest = idRest;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_rest", nullable=false, length=10)
    public Date getDateRest() {
        return this.dateRest;
    }
    
    public void setDateRest(Date dateRest) {
        this.dateRest = dateRest;
    }

    
    @Column(name="montant_rest", nullable=false, precision=22, scale=0)
    public double getMontantRest() {
        return this.montantRest;
    }
    
    public void setMontantRest(double montantRest) {
        this.montantRest = montantRest;
    }

    
    /*@Column(name="id_client", nullable=false)
    public int getIdClient() {
        return this.idClient;
    }
    
    public void setIdClient(int idClient) {
        this.idClient = idClient;
    }*/

    
    @Column(name="nom_societe", nullable=false, length=50)
    public String getNomSociete() {
        return this.nomClient;
    }
    
    public void setNomSociete(String nomSociete) {
        this.nomClient = nomSociete;
    }
     @Column(name = "id_salarie", nullable = false)
     public String getNomClient() {
        return nomClient;
    }

    public void setNomClient(String nomClient) {
        this.nomClient = nomClient;
    }





}


