package mapping;
// Generated 15 janv. 2018 23:23:09 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Salarie generated by hbm2java
 */
@Entity
@Table(name = "salarie", catalog = "notesdefrais"
)
public class Salarie implements java.io.Serializable {

    public static Integer idSalarie;
    public static String nomSalarie;
    private String prenomSalarie;
    private String emailSalarie;
    private String mdpSalarie;

    public Salarie() {
    }

    public Salarie(String nomSalarie, String prenomSalarie, String emailSalarie, String mdpSalarie) {
        this.nomSalarie = nomSalarie;
        this.prenomSalarie = prenomSalarie;
        this.emailSalarie = emailSalarie;
        this.mdpSalarie = mdpSalarie;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id_salarie", nullable = false)
    public Integer getIdSalarie() {
        return this.idSalarie;
    }

    public void setIdSalarie(Integer idSalarie) {
        this.idSalarie = idSalarie;
    }

    @Column(name = "nom_salarie", nullable = false, length = 50)
    public String getNomSalarie() {
        return this.nomSalarie;
    }

    public void setNomSalarie(String nomSalarie) {
        this.nomSalarie = nomSalarie;
    }

    @Column(name = "prenom_salarie", nullable = false, length = 50)
    public String getPrenomSalarie() {
        return this.prenomSalarie;
    }

    public void setPrenomSalarie(String prenomSalarie) {
        this.prenomSalarie = prenomSalarie;
    }

    @Column(name = "email_salarie", unique = true, nullable = false, length = 50)
    public String getEmailSalarie() {
        return this.emailSalarie;
    }

    public void setEmailSalarie(String emailSalarie) {
        this.emailSalarie = emailSalarie;
    }

    @Column(name = "mdp_salarie", nullable = false, length = 50)
    public String getMdpSalarie() {
        return this.mdpSalarie;
    }

    public void setMdpSalarie(String mdpSalarie) {
        this.mdpSalarie = mdpSalarie;
    }

}
